language: python
sudo: false

stages:
  - deploy

credentials:
  - &pypi
    provider: pypi
    user: eduardomourar
    password:
      secure: DmfiiGDMdq1Kgv/i1h8MVuH6QV4cYwSFuslq1BtVLFkwkDeX/s3pFMc7u3xFjaUFdOeWknVBxM0t+c+TRviUyIKGrgDDJM5kMn83h6GgKJ+J+LDVBRVV7/8Zth+yS8vPQWd8cS/t1Nyk2qa92L1X1Z+uNl+/dZa/hLNPAT14QLCdMjniX42J5STCgeBDtKKIXDfrvU9MDFk7n5Asj7Lwi5Nj//YPh2SD95ii6O7fY1BeJQ8aYOqJbfkLD/YDQC5cvpS2A2bwdZWWX0cOrVqix1X6jj0M7CHiCd8rlU9TbqLB1BTo6M7TqwBYmmzdcfJz3IpzWM3SEUHehKPAAZeLzKWzMdeIDUL5yOGFR+7vmfoY5nx3PnskXXV6IbEVYqcLZfn1tEFpz3R++ww4cPPtpaMvEquTXSAoT/m63/YGb17oXq4yLXcTDMv4O2Ka8qWDIGxr6vIorlxRFS+B1nEjhEVVAC6FqJ9mCW8hr4YuDhZweOoPKnBTzYhZgmRO0sfh6L0eiUaIQaNR0/Gfdua0UcCgB0QrH+21jP0zmiONoqsCOMJB7zHWr8yiKQMOEj5J+p561MNrMlqcYfnOGpvuZmvRbzKNj9JZXUgnWZG6IPQxwYeqkkmGzCWVmS4bRTlbvNL7jDprInWWxbdhNhwkiI7bp++BvJDGMYQcNs/LplY=
    on:
      branch: master
      tags: true
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
script:
  - python setup.py install

jobs:
  include:
    - &deploy
      stage: deploy
      name: 'modern distributions'
      python: '3.6'
      install:
      - pip install -U pip setuptools wheel
      # script: skip
      deploy:
        <<: *pypi
        distributions: 'sdist bdist_wheel'

    - <<: *deploy
      name: 'python eggs 2.7'
      python: '2.7'
      deploy:
        <<: *pypi
        distributions: 'bdist_egg'
    - <<: *deploy
      name: 'python eggs 3.4'
      python: '3.4'
      deploy:
        <<: *pypi
        distributions: 'bdist_egg'
    - <<: *deploy
      name: 'python eggs 3.5'
      python: '3.5'
      deploy:
        <<: *pypi
        distributions: 'bdist_egg'
    - <<: *deploy
      name: 'python eggs 3.6'
      python: '3.6'
      deploy:
        <<: *pypi
        distributions: 'bdist_egg'

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit
